version: "3.9"
services:
  streamlit-app:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8502:8502"
    command: >
      bash -c "apt update && apt install -y ffmpeg wget &&
               pip install streamlit opencv-python-headless pandas numpy altair yt-dlp &&
               streamlit run model_pipeline/streamlit_page.py --server.port=8502 --server.address=0.0.0.0"