version: '3.8'

volumes:
  coco:

services:
  extract-extra-data:
    container_name: etl_upload_extra_data
    image: python:3.11
    user: root
    volumes:
      - coco:/data
    working_dir: /data
    command:
      - bash
      - -c
      - |
        set -e
        echo "Resetting dataset directories..."
        rm -rf dataset annotations
        mkdir -p dataset annotations

        echo "Downloading archive..."
        curl -L 'https://nyu.box.com/shared/static/6hhmkdk9eviqaht1rnxn9qt00ccjq1ux.zip' -o /data/labels.zip
        ls -l /data

        echo "Unzipping dataset..."
        unzip -q labels.zip
        rm -f labels.zip

        echo "Listing contents of /data after extract stage:"
        ls -l /data

  load-extra-data:
    container_name: etl_upload_extra_data
    image: rclone/rclone:latest
    user: root
    volumes:
      - coco:/data
      - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
    entrypoint: /bin/sh
    command:
      - -c
      - |
        set -e

        rclone purge chi_tacc:$RCLONE_CONTAINER/val2017
        rclone purge chi_tacc:$RCLONE_CONTAINER/train2017
        echo "Uploading /data/labels → remote:$RCLONE_CONTAINER/labels"
        rclone copy /data/labels chi_tacc:$RCLONE_CONTAINER/labels
          --progress --transfers=8 --checkers=8 -v --fast-list

        echo "Upload complete. Listing remote:"
        rclone lsf chi_tacc:$RCLONE_CONTAINER