apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-infer
  labels:
    app: cpu-infer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-infer
  template:
    metadata:
      labels:
        app: cpu-infer
    spec:
      containers:
        - name: fastapi
          image: vc411892/cpu-infer:latest
          ports:
            - containerPort: 5000
          env:
            - name: MODEL_URL
              value: http://129.114.25.200:30001/models/best.pt
            - name: AWS_ACCESS_KEY_ID
              value: minioadmin
            - name: AWS_SECRET_ACCESS_KEY
              value: miniopassword

---
apiVersion: v1
kind: Service
metadata:
  name: cpu-infer
spec:
  type: NodePort
  selector:
    app: cpu-infer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500

