apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-infer
  labels:
    app: cpu-infer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-infer
  template:
    metadata:
      labels:
        app: cpu-infer
      annotations:
        redeploy-ts: "2025-05-10-16:00"
    spec:
      containers:
        - name: fastapi
          image: vc411892/cpu-infer:latest
          ports:
            - containerPort: 5000
