auth:
  rootUser: minioadmin
  rootPassword: minioadmin

persistence:
  enabled: true
  mountPath: /data

extraVolumeMounts:
  - name: host-minio-data
    mountPath: /data

extraVolumes:
  - name: host-minio-data
    hostPath:
      path: /mnt/minio-data
      type: Directory

nodeSelector:
  kubernetes.io/hostname: k8s-worker-0

mode: standalone

resources:
  requests:
    memory: 512Mi
    cpu: 250m

service:
  type: ClusterIP
  ports:
    api: 9000
    console: 9001

volumePermissions:
  enabled: true
