apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 16.0.8
    helm:
      values: |
        auth:
          rootUser: minioadmin
          rootPassword: miniopassword
        mode: standalone

        persistence:
          enabled: true
          existingClaim: minio-pvc

        defaultBuckets: mlflow

        service:
          type: NodePort
          nodePorts:
            api: 30000
            console: 30001

        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 10

        nodeSelector:
          kubernetes.io/hostname: k8s-master-0

        podSecurityContext:
          fsGroup: 1001

        extraEnvVars:
          - name: MINIO_SERVER_URL
            value: "http://129.114.25.200:30000"
          - name: BITNAMI_DEBUG
            value: "true"


  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
