apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 13.6.1
    helm:
      values: |
        auth:
          rootUser: admin
          rootPassword: admin
        mode: standalone
        persistence:
          enabled: true
          existingClaim: minio-pvc
        service:
          type: NodePort
          nodePorts:
            api: 30000
            console: 30001
        nodeSelector:
          kubernetes.io/hostname: k8s-worker-0
        podSecurityContext:
          fsGroup: 1001
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: minio-api
          initialDelaySeconds: 120
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: minio-api
          initialDelaySeconds: 120
          periodSeconds: 10
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
