apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: 0.17.2
    helm:
      values: |
        artifactRoot: s3://mlflow-artifacts
        defaultArtifactRoot: s3://mlflow-artifacts
        backendStore:
          database:
            postgresql:
              enabled: true
              auth:
                username: mlflow
                password: mlflowpassword
                database: mlflowdb
        extraEnv:
          - name: MLFLOW_S3_ENDPOINT_URL
            value: http://129.114.25.200:30001/
          - name: AWS_ACCESS_KEY_ID
            value: minioadmin
          - name: AWS_SECRET_ACCESS_KEY
            value: miniopassword
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
