apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: 0.17.2
    helm:
      values: |
        flaskServerSecretKey: ""

        artifactRoot:
          s3:
            enabled: true
            bucket: mlflow
            awsAccessKeyId: minioadmin
            awsSecretAccessKey: miniopassword

        backendStore:
          defaultSqlitePath: /mlflow/mlruns.db

        extraEnvVars:
          MLFLOW_S3_ENDPOINT_URL: http://129.114.25.200:30000
          AWS_ACCESS_KEY_ID: minioadmin
          AWS_SECRET_ACCESS_KEY: miniopassword

        service:
          type: NodePort
          port: 5000
          name: http
          annotations: {}

        nodeSelector:
          kubernetes.io/hostname: k8s-master-0

  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
