apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 27.13.0
    helm:
      values: |
        server:
          enabled: true  
          service:
            type: NodePort
            nodePort: 30090
          nodeSelector:
            kubernetes.io/hostname: k8s-master-0

          persistentVolume:
            enabled: true
            existingClaim: prometheus-server

        serverFiles:
          prometheus.yml:
            scrape_configs:
              - job_name: 'prometheus'
                static_configs:
                  - targets: ['localhost:8001']
              - job_name: 'image-infer'
                static_configs:
                  - targets: ['129.114.27.202:30501']
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
